name: Archer
main: me.asofold.bpl.archer.Archer
version: 1.1.4

commands:
  archer:
    description: 'Commands to subscribe for archer services.'
    usage: '/<command>.... + notify | reload | contest ...|'
    permission: archer.access.command.archer

permissions:
  
  archer.access.command.archer:
    description: Access the archer command(s) at all.
    default: op
  
  archer.access.command.contest:
    description: Access the archer/contest command(s) at all.
    default: op
    children:
      archer.access.command.archer: true
  
  archer.command.contest.join:
    description: Allow to join a contest with a command.
    default: op
    children:
      archer.access.command.contest: true
  
  archer.command.contest.leave:
    description: Allow to leave a contest with a command.
    default: op
    children:
      archer.access.command.contest: true
  
  archer.command.contest.end:
    description: Allow to force contests to end.
    default: op
    children:
      archer.access.command.contest: true
  
  archer.notify:
    description: Toggle notifications about hitting targets (and possibly other).
    default: op
    children:
      archer.access.command.archer: true
  
  archer.reload:
    description: Reload the configuration.
    default: op
    children:
      archer.access.command.archer: true
  
  archer.normaluser:
    description: All permissions for a normal user, whatever that is. May use features but not create contests.
    default: true
    children:
      archer.notify: true
      archer.command.contest.join: true
      archer.command.contest.leave: true

