name: Archer
main: me.asofold.bpl.archer.Archer
version: 1.0.0
depend:
- PluginLibSharedLibrary

commands:
  archer:
    description: 'Commands to subscribe for archer services.'
    usage: '/archer.... for: notify | reload'