name: Archer
main: me.asofold.bukkit.archer.Archer
version: 0.2.0
depend:
- PluginLibSharedLibrary

commands:
  archer:
    description: 'Commands to subscribe for archer services.'
    usage: '/archer.... for: notify | reload'